version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lunch_app
      - MYSQL_USER=lunch_app
      - MYSQL_PASSWORD=lunch_app
  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['.:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    volumes: ['.:/var/www/symfony:cached']
